name: FTP Deploy Laravel to cPanel

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  ftp-deploy:
    name: Upload to FTP server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, intl, pdo, pdo_mysql, openssl

      - name: Install Composer dependencies
        run: |
          composer install --no-dev --optimize-autoloader

      - name: Upload via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{secrets.server_dir}}
